import { Button } from '@/components/ui/button'
import Icon from '@/components/ui/icon'
import { formatNumber, type MultiStopRoute } from '@/lib/routes'

export function MultiStopList({ routes }: { routes: MultiStopRoute[] }) {
  if (!routes.length) return <div className="hud-panel hud-corners p-10 text-center"><Icon name="Route" size={32} className="mx-auto mb-4 text-primary" /><h3 className="font-display text-lg uppercase tracking-[0.14em]">Многоточечных рейсов не найдено</h3><p className="mx-auto mt-2 max-w-md font-mono text-sm text-muted-foreground">Ослабьте фильтры или увеличьте бюджет/трюм.</p></div>
  return <ol className="space-y-3">{routes.map((chain, i) => <li key={chain.key}><article className="hud-panel relative overflow-hidden p-4 sm:p-5"><div className="grid gap-4 lg:grid-cols-[auto_1fr_auto] lg:items-center"><div className="lg:w-16"><span className="font-display text-2xl font-semibold tabular-nums text-primary/70">{String(i + 1).padStart(2,'0')}</span></div><div><div className="flex flex-wrap items-center gap-2"><h3 className="font-display text-lg font-semibold uppercase tracking-[0.08em]">{chain.legs.length}-этапный рейс</h3>{chain.sources.map((s)=><span key={s} className="border border-border bg-secondary px-2 py-0.5 font-mono text-[10px] uppercase">{s}</span>)}</div><ol className="mt-3 space-y-2">{chain.legs.map((leg, idx)=><li key={`${leg.key}-${idx}`} className="grid grid-cols-[auto_1fr] gap-3 font-mono text-xs"><span className="flex h-6 w-6 items-center justify-center border border-primary/50 text-primary">{idx+1}</span><div><strong className="text-foreground">{leg.from.name} → {leg.to.name}</strong><p className="text-muted-foreground">{leg.commodity.name} · {formatNumber(leg.units)} SCU · +{formatNumber(leg.profit)} aUEC</p></div></li>)}</ol><p className="mt-3 font-mono text-[11px] text-muted-foreground">{chain.systems.join(' → ')}</p></div><div className="border-t border-border pt-3 text-left lg:w-72 lg:border-l lg:border-t-0 lg:pl-5 lg:pt-0 lg:text-right"><p className="font-mono text-[10px] uppercase tracking-[0.18em] text-muted-foreground">Итоговая прибыль</p><p className="font-display text-2xl font-semibold tabular-nums text-success">+{formatNumber(chain.totalProfit)}</p><p className="font-mono text-[11px] text-muted-foreground">капитал после рейса {formatNumber(chain.finalCapital)} aUEC</p></div></div></article></li>)}</ol>
}

export function RouteModeToggle({ mode, onMode, maxStops, onStops }: { mode: 'single'|'multi'; onMode: (v:'single'|'multi')=>void; maxStops: number; onStops:(n:number)=>void }) {
  return <div className="flex flex-wrap items-center gap-2"><Button size="sm" variant={mode==='single'?'default':'outline'} onClick={()=>onMode('single')} className="font-mono text-xs uppercase">A → B</Button><Button size="sm" variant={mode==='multi'?'default':'outline'} onClick={()=>onMode('multi')} className="font-mono text-xs uppercase">Multi-stop</Button>{mode==='multi' && <label className="ml-1 flex items-center gap-2 font-mono text-xs text-muted-foreground">этапов <select value={maxStops} onChange={(e)=>onStops(Number(e.target.value))} className="h-9 border border-input bg-background px-2 text-foreground"><option value={2}>2</option><option value={3}>3</option><option value={4}>4</option></select></label>}</div>
}
